name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create commit
        run: |
          git config --global user.email "deploy@example.com"
          git config --global user.name "github_deploy"
          git checkout -b staging
          git push --force --set-upstream origin staging
